config/routes.rb
Rails.application.routes.draw do

  resources :locations
  mount ActionCable.server => '/cable'
  resources :collections do
    resources :collection_items
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :chatrooms
  resources :messages
  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end
  resources :schedule_items
  resources :companies
  resources :waitlists

 resources :proposals do
  get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
  get '/payment', to: 'proposals#payment'
  get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
  get 'accept_request', to: 'proposals#accept_request'
  get 'approve_request', to: 'proposals#approve_request'
 end
 get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
 get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  # Back admin routes start
  namespace :admin do
    resources :users

    # Admin root
    root to: 'application#index'
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'user/:id', to: "users#show", as: 'user_show'
  get 'adminlte', to:'pages#adminlte'
  resources :charges
  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'

  get '/notifications', to: 'notifications#index', as: 'notifications'

  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  # Application root
  root to: 'application#home'
  # Front routes end
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collection_items
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  layout 'adminlte'
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.where(user: current_user)
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:user_id, :title)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(collection) do |f| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<% @collections.each do |collection| %>
  <div class='row'>
    <div class='row text-center'>
      <h3><%= collection.title %></h3>
    </div>
    <div class='col-md-10'>
      <div class='row'>
        <% collection.collection_items.take(4).each do |item| %>
          <div class='col-md-3' >
            <%= image_tag item.file, class: 'img-responsive' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class='col-md-2' style='vertical-align:center'>
      <%= link_to 'Add To Collection', new_collection_collection_item_path(collection), class: 'btn btn-warning btn-block' %>
      <%= link_to 'View', collection, class: 'btn btn-primary btn-block' %>
      <%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-block' %>
    </div>
  </div>
<% end %>
<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @collection.title %>
</p>
<div class='row'>
  <% @collection.collection_items.each do |item| %>
    <div class='col-md-3'>
      <%= link_to collection_collection_item_path(@collection, item) do %>
        <%= image_tag item.file, style: 'max-height:300px;max-width:200px' %>
      <% end %>
    </div>
  <% end %>
</div>
<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>