config/routes.rb
Rails.application.routes.draw do

  resources :locations
  mount ActionCable.server => '/cable'
  resources :collections do
    resources :collection_items
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :chatrooms
  resources :messages
  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end
  resources :schedule_items
  resources :companies
  resources :waitlists

 resources :proposals do
  get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
  get '/payment', to: 'proposals#payment'
  get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
  get 'accept_request', to: 'proposals#accept_request'
  get 'approve_request', to: 'proposals#approve_request'
 end
 get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
 get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  # Back admin routes start
  namespace :admin do
    resources :users

    # Admin root
    root to: 'application#index'
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'user/:id', to: "users#show", as: 'user_show'
  get 'adminlte', to:'pages#adminlte'
  resources :charges
  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'

  get '/notifications', to: 'notifications#index', as: 'notifications'

  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  # Application root
  root to: 'application#home'
  # Front routes end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :tasks
  mount_uploader :logo, LogoUploader
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create, :show]
  layout 'adminlte'

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order(:created_at).page params[:page]
    render :layout => 'adminlte'
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    render :layout => 'adminlte'
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    render :layout => 'adminlte'
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        if current_user.user_type == 'company'
          current_user.company = @company
          current_user.save
          byebug
        end
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :logo, :phone, :website)
    end

    def authorize
      unless current_user.company == @company
        redirect_to adminlte_path
      end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group has-feedback">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Company Name' %>
    <span class='glyphicon glyphicon-user form-control-feedback'></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.file_field :logo, class: 'form-control' %>
    <span class='glyphicon glyphicon-picture form-control-feedback'></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Company Phone Number' %>
    <span class='glyphicon glyphicon-phone form-control-feedback'></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.text_field :website, class: 'form-control', placeholder: 'Website - www.example.com' %>
    <span class='glyphicon glyphicon-globe form-control-feedback'></span>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.logo %></td>
        <td><%= company.phone %></td>
        <td><%= company.website %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">

      <!-- Profile Image -->
      <%= render 'companies/partials/company_info_top' %>
      <!-- /.box -->

      <!-- About Me Box -->
      <%= render 'companies/partials/company_info_bottom' %>
      <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
          <li><a href="#timeline" data-toggle="tab">Timeline</a></li>
          <li><a href="#settings" data-toggle="tab">Settings</a></li>
        </ul>
        <div class="tab-content">
          <div class="active tab-pane" id="activity">
            Something Goes Here
          </div>
          <!-- /.tab-pane -->
          <div class="tab-pane" id="timeline">
            Something else goes here
          </div>
          <!-- /.tab-pane -->

          <div class="tab-pane" id="settings">
            Some More Shit Goes Here
          </div>
          <!-- /.tab-pane -->
        </div>
        <!-- /.tab-content -->
      </div>
      <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>