config/routes.rb
Rails.application.routes.draw do

  resources :locations
  mount ActionCable.server => '/cable'
  resources :collections do
    resources :collection_items
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :chatrooms
  resources :messages
  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end
  resources :schedule_items
  resources :companies
  resources :waitlists

 resources :proposals do
  get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
  get '/payment', to: 'proposals#payment'
  get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
  get 'accept_request', to: 'proposals#accept_request'
  get 'approve_request', to: 'proposals#approve_request'
 end
 get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
 get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  # Back admin routes start
  namespace :admin do
    resources :users

    # Admin root
    root to: 'application#index'
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'user/:id', to: "users#show", as: 'user_show'
  get 'adminlte', to:'pages#adminlte'
  resources :charges
  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'

  get '/notifications', to: 'notifications#index', as: 'notifications'

  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  # Application root
  root to: 'application#home'
  # Front routes end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :company
  belongs_to :user, optional: true
  belongs_to :location
  has_many :tasks
  has_many :proposal_requests
  has_one :chatroom
  paginates_per 20
  mount_uploader :model_release, FileUploader

  def find_creatives
    creatives =[]
    search_date = Date.today
    creatives = ScheduleItem.where(location: self.location).where("end_date > ?", search_date).map{|si|
      ProposalSearchResult.new(user_id: si.user.id, rank: 3, schedule_item_id: si.id)
    }
    unless self.location.parent_id.nil?
      ScheduleItem.where(location_id: self.location.parent_id).where("end_date > ?", search_date).map{|si|
        creatives << ProposalSearchResult.new(user_id: si.user.id, rank: 2, schedule_item_id: si.id)
      }
    end
    return creatives.sort! { |a, b|  b.rank <=> a.rank }
  end

  def create_tasks
    if self.proposal_type = "Photo"
      self.tasks.create!(company: self.company, description: "Photo Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Photo Task 2", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Photo Task 3", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Photo Task 4", deadline: self.deadline, completed: false)
    elsif self.proposal_type == "Video"
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
    elsif self.proposal_type == "Drone"
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :edit_details, :payment, :update, :destroy]
  layout 'adminlte'

  # GET /proposals
  # GET /proposals.json
  def index
    if current_user.user_type == 'creative'
      @proposals = Proposal.where(user: current_user).where(completed: nil).order(:created_at).page params[:page]
    else
      @proposals = Proposal.where(company: current_user.company).order(:created_at).page params[:page]
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @notifications = Notification.where(user: current_user).where(notification_obeject_id: params[:id]).where(read: false)
    @notifications.each do |note|
      note.read = true
      note.save
    end
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  def edit_details
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)
    respond_to do |format|
      if @proposal.save
        set_price(@proposal)
        @chatroom = Chatroom.create!(topic: @proposal.title, proposal: @proposal)
        @chatroom.messages.create!(user: current_user, content: "#{@proposal.company.name}' - '#{@proposal.title} Chat Was Created")
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.accepted == true
        format.html { redirect_to @proposal, notice: 'The Proposal Can Not Be Changed After It Has Been Assigned' }
      end
      unless params[:proposal][:bts].nil? || params[:proposal][:bts].count == 0
        @proposal.bts.clear
        params[:proposal][:bts].each do |bt|
          @proposal.bts << bt
        end
      end
      unless params[:proposal][:focus_points].nil? || params[:proposal][:focus_points].count == 0
        @proposal.focus_points.clear
        params[:proposal][:focus_points].each do |fp|
          @proposal.focus_points << fp
        end
      end
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment
  end

  def requests
    if current_user.user_type == 'creative'
      @requests = ProposalRequest.where(requested: current_user.id)
    end
  end

  def create_request
    @proposal = Proposal.find(params[:proposal_id])
    @requested = User.find(params[:user_id])
    @proposal_request = ProposalRequest.where(requested: @requested.id, proposal_id: @proposal.id ).first
    if @proposal_request.nil?
      @proposal_request = ProposalRequest.create(requested_by: current_user.id, requested: @requested.id, proposal_id: @proposal.id )
    end
    send_notification(@requested.id, "New Request", @proposal_request.id)
    redirect_to @proposal
  end

  def accept_request
    @proposal = Proposal.find(params[:proposal_id])
    @proposal_request = ProposalRequest.where(requested: current_user.id, proposal_id: @proposal.id ).first
    @proposal_request.accepted = true
    @proposal_request.save
    send_notification(@proposal_request.requested_by, "Request Accepted", @proposal.id)
    redirect_to proposal_requests_path
  end

  def approve_request
    @proposal = Proposal.find(params[:proposal_id])
    @proposal_request = ProposalRequest.where(requested_by: current_user.id, proposal_id: @proposal.id, accepted: true).first
    @proposal_request.approved = true
    @proposal_request.save
    @proposal.accepted = true
    @proposal.user = User.find(@proposal_request.requested)
    @proposal.save
    @proposal.create_tasks
    @proposal.tasks.each do |task|
      task.user_id = @proposal_request.requested
      task.save
    end
    @proposal.chatroom.messages.create!(user: @proposal.user, content: "#{@proposal.user.name has been added to the chat}")
    send_notification(@proposal_request.requested, "Proposal Assigned", @proposal.id)
    send_notification(@proposal_request.requested, "Task", @proposal.id)
    redirect_to @proposal
  end

  def completed
    if current_user.user_type.downcase == 'creative'
      @proposals = Proposal.where(user: current_user).where(completed: true).order(:completed_on).reverse
    else
      @proposals = Proposal.where(company: current_user.company).where(completed: true).order(:completed_on).reverse
    end
  end

  private
    def send_notification(user_id, notification_type, request_id)
      notification = Notification.where(user_id: user_id, notification_type: notification_type, notification_obeject_id: request_id).first
      if notification.nil?
        notification = Notification.create!(user_id: user_id, notification_type: notification_type, notification_obeject_id: request_id, read: false)
      end
    end

    def set_price(proposal)
      if proposal.proposal_type == 'photo'
        proposal.price =  4000
      elsif proposal.proposal_type == 'video'
        proposal.price =  4000
      elsif proposal.proposal_type == 'drone'
        proposal.price =  1000
      end
      proposal.save
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      unless params[:id].nil?
        @proposal = Proposal.find(params[:id])
      else
        @proposal = Proposal.find(params[:proposal_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:title, :content, :deadline, :price, :accepted, :company_id, :proposal_type, :completed, :completed_on, :paid, :charge_id, :bts, :focus_points, :time_of_day, :location_id, :background, :model_release)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/partials/_balance_payment.html.erb
<section class="invoice">
      <!-- title row -->
      <div class="row">
        <div class="col-xs-12">
          <h2 class="page-header">
            <i class="fa fa-globe"></i> Nomadic Creative
            <small class="pull-right">Date: <%= Date.today %></small>
          </h2>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          From
          <address>
            <strong>Nomadic Creative</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            Phone: (804) 123-5432<br>
            Email: finance@nomcre.com
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          To
          <address>
            <strong><%= @proposal.company.name %></strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            Phone: (555) 539-1037<br>
            Email: <%= @proposal.company.users.first.email %>
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>Invoice #007612</b><br>
          <br>
          <b>Order ID:</b> 4F3S8J<br>
          <b>Payment Due:</b> 2/22/2014<br>
          <b>Account:</b> 968-34567
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Table row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Title</th>
              <th>Deadline</th>
              <th>Type</th>
              <th>Location</th>
              <th>Subtotal</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td><%= @proposal.title %></td>
              <td><%= @proposal.deadline %></td>
              <td><%= @proposal.proposal_type %></td>
              <td><%= @proposal.location.name %></td>
              <td>$<%= @proposal.price * 0.99 %> USD</td>
            </tr>
            </tbody>
          </table>
            </tbody>
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <div class="row">
        <!-- accepted payments column -->
        <div class="col-xs-6">
          <p class="lead">Payment Methods:</p>
          <i class='fa fa-cc-visa fa-3x'></i>
          <i class='fa fa-cc-mastercard fa-3x'></i>
          <i class='fa fa-cc-amex fa-3x'></i>


          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg
            dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
          </p>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
          <p class="lead"><%= Date.today %></p>

          <div class="table-responsive">
            <table class="table">
              <tbody><tr>
                <th style="width:50%">Subtotal:</th>
                <td>$<%= @proposal.price * 0.99 %> USD</td>
              </tr>
            </tbody></table>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- this row will not appear when printing -->
      <div class="row no-print">
        <div class="col-xs-12">
          <!-- <a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a> -->
          <!-- <button type="button" class="btn btn-success pull-right"><i class="fa fa-credit-card"></i> Submit Payment
          </button> -->
          <div class='pull-right'>
            <% if @proposal.paid == false || @proposal.paid == nil%>
              <%= form_tag proposal_balance_path(@proposal) do %>
                <article>
                  <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                  <% end %>
                </article>
                <% @stripe_price = ((@proposal.price - (@proposal.price * 0.01)) * 100)%>
                <form action="/charge" method="POST">
                  <%= hidden_field_tag 'proposal_id', @proposal.id %>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button pull-right"
                  Stripe.setPublishableKey('PUBLISHABLE_KEY');
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Proposal Payment"
                  data-amount="<%= @stripe_price %>"
                  data-locale="auto"></script>
                </form>
              <% end %>
            <% else %>
              <%= link_to 'Paid', root_path, class: 'btn btn-success disabled'%>
            <% end %>
          </div>
          <!-- <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
            <i class="fa fa-download"></i> Generate PDF
          </button> -->
        </div>
      </div>
    </section>

app/views/proposals/partials/_company_proposal_view.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">

      <!-- Profile Image -->
      <%= render 'proposals/partials/proposal_info_top' %>
      <!-- /.box -->

      <!-- About Me Box -->
      <%= render 'proposals/partials/proposal_info_bottom' %>
      <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#basic_info" data-toggle="tab">Basic Info</a></li>
          <li><a href="#details" data-toggle="tab">Details</a></li>
          <li><a href="#tasks" data-toggle="tab">Tasks</a></li>
          <li><a href="#creatives" data-toggle="tab">Suggested Creatives</a></li>
          <li><a href="#disclosures" data-toggle="tab">Disclosures</a></li>
          <li><a href="#invoice" data-toggle="tab">Invoice</a></li>
        </ul>
        <div class="tab-content">
          <div class="active tab-pane" id="basic_info">
            <%= render 'proposals/partials/proposal_basic_info'%>
          </div>
          <div class="tab-pane" id="details">
            <%= render 'proposals/partials/proposal_details'%>
          </div>
          <div class="tab-pane" id="tasks">
            <%= render 'proposals/partials/proposal_tasks_list'%>
          </div>
          <div class="tab-pane" id="creatives">
            <%= render 'proposals/partials/proposal_search_results' %>
          </div>
          <div class="tab-pane" id="disclosures">
            <%= render 'proposals/partials/proposal_disclosures' %>
          </div>
           <div class="tab-pane" id="invoice">
            Invoice Goes Here
          </div>
          <!-- /.tab-pane -->
        </div>
        <!-- /.tab-content -->
      </div>
      <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>

app/views/proposals/partials/_creative_proposal_view.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">

      <!-- Profile Image -->
      <%= render 'proposals/partials/proposal_info_top_creative' %>
      <!-- /.box -->

      <!-- About Me Box -->
      <%= render 'proposals/partials/proposal_info_bottom' %>
      <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#basic_info" data-toggle="tab">Basic Info</a></li>
          <li><a href="#details" data-toggle="tab">Details</a></li>
          <li><a href="#tasks" data-toggle="tab">Tasks</a></li>
          <li><a href="#disclosures" data-toggle="tab">Disclosures</a></li>
        </ul>
        <div class="tab-content">
          <div class="active tab-pane" id="basic_info">
            <%= render 'proposals/partials/proposal_basic_info'%>
          </div>
          <div class="tab-pane" id="details">
            <%= render 'proposals/partials/proposal_details'%>
          </div>
          <div class="tab-pane" id="tasks">
            <%= render 'proposals/partials/proposal_tasks_list'%>
          </div>
          <div class="tab-pane" id="disclosures">
            <%= render 'proposals/partials/proposal_disclosures' %>
          </div>
          <!-- /.tab-pane -->
        </div>
        <!-- /.tab-content -->
      </div>
      <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>

app/views/proposals/partials/_proposal_basic_info.html.erb
<div class="box box-solid">
<!-- /.box-header -->
<div class="box-body">
  <div class='row'>
    <dl style="padding:12px">
      <dt>
        Production Type
      </dt>
      <dd>
        <%= @proposal.proposal_type%>
      </dd>
    </dl>
  </div>
  <hr/>
  <dl>
    <dt>Creative Brief</dt>
    <dd><%= @proposal.content%></dd>
  </dl>
</div>
<!-- /.box-body -->
<div class="pull-right">
  <%= link_to "Edit", edit_proposal_path(@proposal) unless  @proposal.company.users.include?(current_user) == false %>
</div>
</div>

app/views/proposals/partials/_proposal_details.html.erb
<div class="box box-solid">
  <div class='row'>
    <div class='col-md-6'>
      <div class="panel box box-primary">
        <div class="box-header with-border">
          <h4 class="box-title">Focus Points</h4>
        </div>
        <div class="box-body">
         <ul>
         <% @proposal.focus_points.each do  |fp| %>
          <li><%= fp %></li>
         <% end %>
       </ul>
        </div>
      </div>
      <div class="panel box box-primary">
        <div class="box-header with-border">
          <h4 class="box-title">Background / TOD</h4>
        </div>
        <div class="box-body">
          <strong>Background</strong><%= @proposal.background %>
          <hr>
          <strong>Time Of Day </strong><%= @proposal.time_of_day %>
        </div>
      </div>
    </div>
    <div class='col-md-6'>
      <div class="panel box box-primary">
        <div class="box-header with-border">
          <h4 class="box-title">Behind The Scenes</h4>
        </div>
        <div class="box-body">
           <ul>
             <% @proposal.bts.each do |bts| %>
             <li> <%= bts %> </li>
             <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% if current_user.company == @proposal.company %>
      <%= link_to "Edit", proposal_edit_details_path(@proposal), class: 'pull-right' unless  @proposal.company.users.include?(current_user) == false %>
    <% end %>
</div>

app/views/proposals/partials/_proposal_disclosures.html.erb
<%= form_for(@proposal) do |f| %>
  <div class="field">
    <%= f.label :model_release %>
    <%= f.file_field :model_release %>
  </div>
  <%= f.submit %>
<% end %>


<% unless @proposal.model_release.nil? %>
  <%= image_tag @proposal.model_release, class: 'img-responsive'%>
<% end %>

app/views/proposals/partials/_proposal_info_bottom.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">About us</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

    <p class="text-muted">
      <%= @proposal.location.name %>
    </p>
    <hr>
    <strong><i class="fa fa-globe margin-r-5"></i> Website</strong>
    <p class="text-muted"><%= @proposal.company.website %></p>
    <hr>
    <!-- <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>
    <p>
      <span class="label label-danger">UI Design</span>
      <span class="label label-success">Coding</span>
      <span class="label label-info">Javascript</span>
      <span class="label label-warning">PHP</span>
      <span class="label label-primary">Node.js</span>
    </p>
    <hr>

    <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p> -->
  </div>
  <!-- /.box-body -->
</div>

app/views/proposals/partials/_proposal_info_top.html.erb
<div class="box box-primary">
  <div class="box-body box-profile">
    <% unless @proposal.company.nil? %>
      <%= image_tag @proposal.company.logo, class: 'profile-user-img img-responsive img-circle'%>
    <% end %>
    <h3 class="profile-username text-center"> <%= @proposal.title %></h3>

    <!-- <p class="text-muted text-center">Software Engineer</p> -->

    <ul class="list-group list-group-unbordered">
      <li class="list-group-item">
        <b>Deadline</b> <a class="pull-right"><%= @proposal.deadline %></a>
      </li>
      <li class="list-group-item">
        <b>Is Paid</b> <a class="pull-right"><%= @proposal.paid? %></a>
      </li>
      <li class="list-group-item">
        <b>Complete</b> <a class="pull-right"><%= @proposal.completed? %></a>
      </li>
      <li class="list-group-item">
        <b>Assigned To</b> <a class="pull-right"><%= @proposal.user.email unless @proposal.user.nil? %></a>
      </li>
    </ul>

    <% if (current_user.company ==  @proposal.company) && @proposal.accepted != true %>
      <%= link_to 'Edit', edit_proposal_path(@proposal), class: "btn btn-primary btn-block" %>
    <% end %>
    <%= link_to 'Chat', chatroom_path(@proposal.chatroom), class: "btn btn-primary btn-block" %>
    <% if  @proposal.deposit_paid == true %>
      <%= link_to 'Deposit Paid', "#", class: "btn btn-success btn-block disabled" %>
    <% else %>
      <%= link_to 'Pay Depost', proposal_payment_path(@proposal), class: "btn btn-warning btn-block" %>
    <% end %>
     <% if  @proposal.paid == true %>
      <%= link_to 'Balance Paid', proposal_payment_path(@proposal), class: "btn btn-success btn-block disabled" %>
    <% else %>
      <% if @proposal.deposit_paid == true %>
        <%= link_to 'Pay', proposal_payment_path(@proposal), class: "btn btn-warning btn-block" %>
      <% else %>
        <%= link_to 'Deposit Required First', "#", class: "btn btn-warning btn-block disabled" %>
      <% end %>
    <% end %>
  </div>
  <!-- /.box-body -->
</div>

app/views/proposals/partials/_proposal_info_top_creative.html.erb
<div class="box box-primary">
  <div class="box-body box-profile">
    <% unless @proposal.company.nil? %>
      <%= image_tag @proposal.company.logo, class: 'profile-user-img img-responsive img-circle'%>
    <% end %>
    <h3 class="profile-username text-center"> <%= @proposal.title %></h3>

    <!-- <p class="text-muted text-center">Software Engineer</p> -->

    <ul class="list-group list-group-unbordered">
      <li class="list-group-item">
        <b>Deadline</b> <a class="pull-right"><%= @proposal.deadline %></a>
      </li>
      <li class="list-group-item">
        <b>Is Paid</b> <a class="pull-right"><%= @proposal.paid? %></a>
      </li>
      <li class="list-group-item">
        <b>Complete</b> <a class="pull-right"><%= @proposal.completed? %></a>
      </li>
      <li class="list-group-item">
        <b>Assigned To</b> <a class="pull-right"><%= @proposal.user.email unless @proposal.user.nil? %></a>
      </li>
    </ul>
  </div>
  <!-- /.box-body -->
</div>

app/views/proposals/partials/_proposal_search_results.html.erb
<% unless @proposal.deposit_paid %>
  <p> Deposit Must Be Paid Prior To Requesting Creatives </p>
<% end %>
<% @proposal.find_creatives.each do |sr| %>
  <div class='row'>
    <div class='col-md-3'><%= sr.user.name %></div>
    <div class='col-md-3'><%= sr.schedule_item.end_date %></div>
    <div class='col-md-3'><%= link_to "See Portfolio", user_show_path(sr.user), class: 'btn btn-primary' %></div>
    <div class='col-md-3'>
      <%= render :partial => 'proposals/partials/search_results/request_buttons', :locals => {:sr => sr}%>
    </div>
  </div>
  <div class='row'>
    <% sr.user.collection_items.reverse.take(4).each do |ci| %>
      <div class='col-md-3'>
        <%= image_tag ci.file, class: 'img-responsive' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/proposals/partials/_proposal_tasks_list.html.erb
<ul class="list-unstyled">
<% @proposal.tasks.each do |task| %>
  <li>
    <div class='row'>
      <div class='col-md-4'><%= task.description%></div>
      <div class='col-md-4'><%= task.deadline%></div>
      <div class='col-md-4'>
        <% if  @proposal.company.users.include?(current_user) %>
          <% if task.completed? %>
            <%= link_to "Complete", task_task_complete_path(task), class: 'btn btn-warning disabled btn-block'  %>
          <% else %>
            <%= link_to "Mark Complete", task_task_complete_path(task), class: 'btn btn-primary btn-block'  %>
          <% end %>
        <% end %>

        <%= link_to "View", task %>
      </div>
    </div>
  </li>
<% end %>
</ul>

app/views/proposals/partials/requests.html.erb
<%= render 'proposals/partials/requests/proposal_requests'%>