config/routes.rb
Rails.application.routes.draw do

  resources :locations
  mount ActionCable.server => '/cable'
  resources :collections do
    resources :collection_items
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :chatrooms
  resources :messages
  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end
  resources :schedule_items
  resources :companies
  resources :waitlists

 resources :proposals do
  get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
  get '/payment', to: 'proposals#payment'
  get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
  get 'accept_request', to: 'proposals#accept_request'
  get 'approve_request', to: 'proposals#approve_request'
 end
 get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
 get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  # Back admin routes start
  namespace :admin do
    resources :users

    # Admin root
    root to: 'application#index'
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'user/:id', to: "users#show", as: 'user_show'
  get 'adminlte', to:'pages#adminlte'
  resources :charges
  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'

  get '/notifications', to: 'notifications#index', as: 'notifications'

  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  # Application root
  root to: 'application#home'
  # Front routes end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  belongs_to :proposal
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collection_items
end

app/models/collection_item.rb
class CollectionItem < ApplicationRecord
  belongs_to :user
  belongs_to :collection

  mount_uploader :file, FileUploader
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :tasks
  mount_uploader :logo, LogoUploader
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || 'is not a valid email')
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :parent, :class_name => "Location", :foreign_key => "parent_id", optional: true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :chatroom
  mount_uploader :file, FileUploader
  after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :company
  belongs_to :user, optional: true
  belongs_to :location
  has_many :tasks
  has_many :proposal_requests
  has_one :chatroom
  paginates_per 20
  mount_uploader :model_release, FileUploader

  def find_creatives
    creatives =[]
    search_date = Date.today
    creatives = ScheduleItem.where(location: self.location).where("end_date > ?", search_date).map{|si|
      ProposalSearchResult.new(user_id: si.user.id, rank: 3, schedule_item_id: si.id)
    }
    unless self.location.parent_id.nil?
      ScheduleItem.where(location_id: self.location.parent_id).where("end_date > ?", search_date).map{|si|
        creatives << ProposalSearchResult.new(user_id: si.user.id, rank: 2, schedule_item_id: si.id)
      }
    end
    return creatives.sort! { |a, b|  b.rank <=> a.rank }
  end

  def create_tasks
    if self.proposal_type = "Photo"
      self.tasks.create!(company: self.company, description: "Photo Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Photo Task 2", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Photo Task 3", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Photo Task 4", deadline: self.deadline, completed: false)
    elsif self.proposal_type == "Video"
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Video Task 1", deadline: self.deadline, completed: false)
    elsif self.proposal_type == "Drone"
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
      self.tasks.create!(company: self.company, description: "Drone Task 1", deadline: self.deadline, completed: false)
    end
  end
end

app/models/proposal_request.rb
class ProposalRequest < ApplicationRecord
  belongs_to :proposal
end

app/models/schedule_item.rb
class ScheduleItem < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :proposal
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  validates :name, presence: true
  validates :email, uniqueness: true, email: true
  belongs_to :company, optional: true
  accepts_nested_attributes_for :company
  has_many :schedule_items
  has_many :collections
  has_many :collection_items
  has_many :proposal_requests
  has_many :tasks
  has_many :messages
  has_many :chatrooms, through: :messages
  has_many :notifications
  mount_uploader :profile_image, ImageUploader

  def set_default_role
    self.role ||= :user
  end

  def has_request(proposal_id)
    ProposalRequest.where(requested: self.id, proposal_id: proposal_id).count > 0
  end

  def get_proposal_request(proposal_id)
    ProposalRequest.where(requested: self.id, proposal_id: proposal_id).first
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
  paginates_per 20
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/proposals/partials/requests/_proposal_requests.html.erb
<% current_user.proposal_requests.each do |pr| %>
  <div class='row'>
    <div class='col-md-3'>
      <%= pr.proposal.title %> <br>
      <%= pr.proposal.company.name %>
    </div>
    <div class='col-md-3'>
      <%= pr.proposal.deadline %>
    </div>
    <div class='col-md-3'> <%= pr.proposal.location.name %></div>
    <div class='col-md-3'> <%= link_to "Show", pr.proposal, class: 'btn btn-primary'%> </div>
  </div>
<% end %>

app/views/proposals/partials/search_results/_request_buttons.html.erb
  <!-- New Layout -->
  <% if @proposal.accepted != true && @proposal.user.nil? %>
    <% puts " No User Has Been Approved  " %>
    <% puts '-------No User Assigned  -------' %>
    <% if @proposal.deposit_paid != true %>
      <% puts " Deposit not yet Paid " %>
      <%= link_to "Deposit Required", "#", class: 'btn btn-primary disabled' %>
    <% else %>
      <% puts " Deposit is already Paid " %>
      <% context_user = User.find(sr.user_id) %>
      <% if context_user.has_request(@proposal.id)%>
        <% puts " A Request Already Exists For This User " %>
        <% if context_user.get_proposal_request(@proposal.id).accepted %>
          <%= link_to "Request Accepted", "#", class: 'btn btn-primary disabled' %>
          <% if @proposal.paid == true %>
            <% puts " proposal is  paid for " %>
            <% if context_user.get_proposal_request(@proposal.id).accepted? %>
              <% puts " Creative Accepted Request " %>
              <%= link_to "Approve", proposal_approve_request_path(@proposal), class: 'btn btn-success btn-block' %>
            <% end %>
          <% else %>
            <% puts " proposal is not paid for " %>
            <%= link_to "Complete Payment", proposal_payment_path(@proposal), class: 'btn btn-warning btn-block' %>
          <% end %>
        <% else %>
          <%= link_to "Already Requested", "#", class: 'btn btn-primary disabled' %>
        <% end %>
      <% else %>
        <% puts " No Request Exists For This User " %>
        <%= link_to "Request Creative", proposal_create_request_path(@proposal, sr.user), class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% else %>
    <% puts '-------Assigned To User -------' %>
    <% puts " A User Is  Approved  " %>
    <% if @proposal.user.id == sr.user_id %>
      <% puts " This Is The Assigned User " %>
        <% puts '-------Assigned To THIS User -------' %>
         <%= link_to "Approved", "#", class: 'btn btn-success disabled' %>
    <% else %>
      <% puts " This Proposal is Assigned To Someone Else " %>
        <% puts '-------Assigned To Different User -------' %>
      <%= link_to "Already Assigned", "#", class: 'btn btn-primary disabled' %>
    <% end %>
  <% end %>

app/views/shared/_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p>Made with ♥ by <a href="https://github.com/dreamingechoes">@nomcre</a>.</p>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= t('navigation.main_title') %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li> <%= link_to t('navigation.root'), root_path %> </li>
        <li> <%= link_to "Login", new_user_session_path %> </li>
        <li> <%= link_to "Logout", destroy_user_session_path,  method: :delete %> </li>
        <li> <%= link_to "Register Company", new_user_registration_path(user_type: 'company') %> </li>
        <li> <%= link_to "Register Creative", new_user_registration_path(user_type: 'creative') %> </li>
        <li> <%= link_to "Join Waitlist", new_waitlist_path %> </li>
        <li> <%= link_to t('navigation.admin'), admin_root_path %> </li>
      </ul>
    </nav>
  </div>
</div>